version: "3.8"
services:
  db:
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5438:5432
    environment:
      - POSTGRES_PASSWORD=qwerty

volumes:
  db_data:
